
import { GoogleGenAI } from "@google/genai";

/**
 * Generates a photorealistic product image using gemini-2.5-flash-image
 */
export async function generateProductImage(productName: string, category: string): Promise<string> {
  // Initialize AI client with the provided environment key
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });
  
  try {
    const prompt = `A professional, high-end studio product photograph of a ${productName} ${category}. The hardware is centered, features cinematic lighting with sharp highlights, highly detailed textures, 8k resolution, photorealistic, clean tech aesthetic, dark minimalist charcoal background, professional commercial photography style.`;
    
    // Using gemini-2.5-flash-image by default for general image generation tasks
    // generateContent is used for nano banana series models
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash-image',
      contents: {
        parts: [
          {
            text: prompt,
          },
        ],
      },
      config: {
        imageConfig: {
          aspectRatio: "1:1",
        },
      },
    });

    // Extract the image from candidates. Iterate parts to find the inlineData containing the image bytes.
    const candidate = response.candidates?.[0];
    if (candidate?.content?.parts) {
      for (const part of candidate.content.parts) {
        if (part.inlineData) {
          const base64EncodeString: string = part.inlineData.data;
          // Format as a base64 data URI for direct usage in image src
          return `data:image/png;base64,${base64EncodeString}`;
        }
      }
    }
    
    throw new Error("No image was generated by the model.");
  } catch (error) {
    console.error("AI Generation Error:", error);
    throw error;
  }
}
